#!/usr/bin/env groovy

// Beautify display
def seperator60 = '\u2739' * 60
def seperator20 = '\u2739' * 20


node('misc'){
      echo "${seperator60}\n${seperator20} Clone repo to workspace \n${seperator60}"
      ansiColor('xterm') {
          checkout scm 
      }
   
      echo "${seperator60}\n${seperator20} Build And Integrate \n${seperator60}"
      stage('Build App'){
        sh "ls -la"
        sh "cd calculator" 
        sh "ls -la" 
      }
}
